# Generated by Django 3.2.16 on 2023-09-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230905_1443'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='Вы уже подписаны',
        ),
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='Нельзя подписаться самому на себя',
        ),
    ]
